// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: posts.sql

package queries

import (
	"context"
)

const createPost = `-- name: CreatePost :one
INSERT INTO posts (slug, title, summary, body)
    VALUES ($1, $2, $3, $4)
RETURNING
    id, slug, title, summary, body, created_at
`

type CreatePostParams struct {
	Slug    string
	Title   string
	Summary string
	Body    string
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, createPost,
		arg.Slug,
		arg.Title,
		arg.Summary,
		arg.Body,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Summary,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}
